import { Routes } from '@angular/router';
import { ButtonExamplesComponent } from './components/button-examples/button-examples.component';
import { InputExamplesComponent } from './components/input-examples/input-examples.component';
import { DataTableExamplesComponent } from './components/data-table-examples/data-table-examples.component';
import { DialogExamplesComponent } from './components/dialog-examples/dialog-examples.component';
import { ChatInputComponent } from './components/chat-input/chat-input.component';
import { ToastExamplesComponent } from './components/toast-examples/toast-examples.component';
import { ScrollExamplesComponent } from './components/scroll-examples/scroll-examples.component';
import { FormExamplesComponent } from './components/form-examples/form-examples.component';
import { DropdownExamplesComponent } from './components/dropdown-examples/dropdown-examples.component';
import { GoogleMapsExamplesComponent } from './components/google-maps-examples/google-maps-examples.component';
import { DataviewExamplesComponent } from './components/dataview-examples/dataview-examples.component';
import { TimelineExamplesComponent } from './components/timeline-examples/timeline-examples.component';
import { DockExamplesComponent } from './components/dock-examples/dock-examples.component';
import { DragDropExamplesComponent } from './components/drag-drop-examples/drag-drop-examples.component';
import { SkeletonExamplesComponent } from './components/skeleton-examples/skeleton-examples.component';
import { InplaceExamplesComponent } from './components/inplace-examples/inplace-examples.component';
import { CarouselExamplesComponent } from './components/carousel-examples/carousel-examples.component';

export const routes: Routes = [
    { path: '', redirectTo: '/buttons', pathMatch: 'full' },
    { path: 'buttons', component: ButtonExamplesComponent },
    { path: 'inputs', component: InputExamplesComponent },
    { path: 'data-table', component: DataTableExamplesComponent },
    { path: 'dialogs', component: DialogExamplesComponent },
    { path: 'chat-input', component: ChatInputComponent },
    { path: 'toast', component: ToastExamplesComponent },
    { path: 'scroll', component: ScrollExamplesComponent },
    { path: 'form', component: FormExamplesComponent },
    { path: 'dropdown', component: DropdownExamplesComponent },
    { path: 'maps', component: GoogleMapsExamplesComponent },
    { path: 'dataview', component: DataviewExamplesComponent },
    { path: 'timeline', component: TimelineExamplesComponent },
    { path: 'dock', component: DockExamplesComponent },
    { path: 'drag-drop', component: DragDropExamplesComponent },
    { path: 'skeleton', component: SkeletonExamplesComponent },
    { path: 'inplace', component: InplaceExamplesComponent },
    { path: 'carousel', component: CarouselExamplesComponent }
];
